### ISSUE TITLE
VirtualHMD id should be always 0

### ISSUE THREAD

**Issue by maxabrahamsson** [infinitellamas/PSMS-OSVR-Connector#2]
I can not get this to work with the Virtual HMD pingpong ball. Because ID for both my 1st controller and Virtual HMD is 0.

In your readme, example configuration has id 1 for Virtual HMD. But according to PSMove service documentation

> Enter the HMD "Device ID" you wish to track
> This will almost always be "0" since you typically only have a single virtual HMD

https://github.com/cboulay/PSMoveService/wiki/Virtual-HMDs

Are you sure this plugin is handling ID correctly?

**Comment by maxabrahamsson** [comment]
I could get 1 controller to act as position for HMD. But I could never get Virtual HMD to position to work.

I test using Tracker View, Sample Scene and SteamVR. Same results.

**Comment by maxabrahamsson** [comment]
My PSMove service version is "Starting PSMoveService v0.9-alpha 8.7.1 (protocol v0.9-alpha 8.7.0)"

**Comment by maxabrahamsson** [comment]
it worked when I switched to older protocol v0.9-alpha 8.4.0 version of the PSMove Service.

Do you have any plans to support the newer version? Why PSMove service is not backwards compatible :(

**Comment by terminal29** [comment]
I don't use it anymore but I am happy to update and fix it so long as people who use it tell me when it breaks again. Give me a week or so and I'll see if i can get it working again.

**Comment by maxabrahamsson** [comment]
Thank you very much mate!

**Comment by terminal29** [comment]
It's going to be a while till I have time to update it sorry, but I will try to get it done as soon as I can.

**Comment by terminal29** [comment]
Ok extended delay over, I will be updating this plugin over the next few days to support the newest osvr server and psmove service.

**Comment by terminal29** [comment]
Ok its finished now, I'm going to close this as it seems to be fixed on my end but if you are still having problems with it feel free to reopen it or make a new issue.

**Comment by maxabrahamsson** [comment]
Thank you mate!
