### ISSUE TITLE
KinectV2+psmoveservice fusion

### ISSUE THREAD

**Issue by nevalonvr** [infinitellamas/PSMS-OSVR-Connector#3]
Hello Infinitellamas, my question is,  can be posibly use orientation from psmoveservice and position from Kinectv2 plugin??
Im Working on that, but nothing work.  I show you my config and if we can help to us and Others.

	"drivers": [{
		"plugin": "inf_osvr_move",
		"driver": "MoveDevice",
		"params": {
			"debug":true,
			"controllers":[
				{
					"name":"controller0",
					"type":"Move",
					"id": 0
				}]
		}
	},
			{
      "plugin": "je_nourish_fusion",
      "driver": "FusionDevice",
      "params": {
        "name": "MoveDevice",
        "position": "/je_nourish_kinect/KinectV2/semantic/body1/right",
        "orientation": "/inf_osvr_move/MoveDevice/semantic/controller0/tracker",
        "offsetFromRotationCenter": {
          "x": 0,
          "y": 0.0,
          "z": 0
        },
        "timestamp": "position"
      }
    },
		{
      "plugin": "je_nourish_fusion",
      "driver": "FusionDevice",
      "params": {
        "name": "DK1_Kinectv2",
        "position": "/je_nourish_kinect/KinectV2/semantic/body1/head",
        "orientation": "/je_nourish_openhmd/Oculus Rift (Devkit)/semantic/hmd",
        "offsetFromRotationCenter": {
          "x": 0,
          "y": 0.0,
          "z": 0
        },
        "timestamp": "position"
      }
    },
	{
			"plugin": "org_osvr_filter_oneeuro",
			"driver": "OneEuroFilter",
			"params": {
				"name": "FilteredRightHand",
				"input": "/je_nourish_fusion/MoveDevice/semantic/controller0/tracker",
				"position": {
					"minCutoff": 1.15,
					"beta": 0.5,
					"derivativeCutoff": 1.2
				},
				"orientation": {
					"minCutoff": 1.5,
					"beta": 0.5,
					"derivativeCutoff": 1.2
				}
			}
		}
	],
	"aliases": {
		"/me/head": "/je_nourish_fusion/DK1_Kinectv2/tracker/0",
		"/me/hands/right": "/inf_osvr_move/MoveDevice/semantic/controller0/tracker"
	}
}

Thanks and good JOB!!!  

Nevalon from Spain

**Comment by nevalonvr** [comment]
Other Cuestion is this fail.

Nov 22 18:52:49.641 error [OSVR Server]: Errors:
Nov 22 18:52:49.641 error [OSVR Server]:  - inf_osvr_move/MoveDevice    Value is not convertible to Int.

**Comment by terminal29** [comment]
If you have verified that separately the trackers work fine, then here is what I think might need changing:
```json
{
  "plugin": "je_nourish_fusion",
  "driver": "FusionDevice",
  "params": {
    "name": "MoveDevice",
    "position": "/je_nourish_kinect/KinectV2/semantic/body1/right",
    "orientation": "/inf_osvr_move/MoveDevice/semantic/controller0/tracker",
    "offsetFromRotationCenter": {
      "x": 0,
      "y": 0.0,
      "z": 0
    },
    "timestamp": "position"
  }
}
```
You haved named your fusion device "MoveDevice" so down in 
```json
"aliases": {
	"/me/head": "/je_nourish_fusion/DK1_Kinectv2/tracker/0",
	"/me/hands/right": "/inf_osvr_move/MoveDevice/semantic/controller0/tracker"
}
```
Your "/me/hands/right" should be "je_nourish_fusion/MoveDevice/tracker/0" instead of being connected directly to the psmove tracker

I'm not sure about your other error sorry
